language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - pandoc
install:
  - pip install Sphinx
  - pip install nbsphinx==0.4.2
  - pip install ipykernel
  - pip install sphinx_rtd_theme
script:
  - python -m sphinx . build/ -b html
  - ./add_html_anchors_to_exercises.py build/*.html
  - touch build/.nojekyll # this file tells gh-pages that there is no need to build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: build
  target-branch: gh-pages 
  on:
    branch: master

notifications:
  email:
    recipients:
      - jarkko.toivonen@cs.helsinki.fi
    on_success: always
    on_failure: always
