language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - pandoc
install:
  - pip install Sphinx
  - pip install sphinxnb
  - pip install ipykernel
script:
  - python -m sphinx . build/ -b html
